### Post prices
POST http://localhost:5000/prices HTTP/1.1
Content-Type: application/json
//token:

{
    "region": "Pirkanmaa",
    "city": "Tampere",
    "company": "Kesoil",
    "address": "Kuja 5",
    "petrol95": "1.456",
    "petrol98": "1.567",
    "diesel": "1.345",
    "ethanol": "1.012"
}
###